openapi: 3.1.0
info:
  version: 1.0.0
  title: Spendy - Expense Tracker App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: API documentation of Spendy Expense Tracker App
tags:
  - name: Users
    description: Operations about users.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://example.com/api/v1
paths:
  /categories:
    get:
      $ref: ../swagger/paths/categories/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
