openapi: 3.1.0
info:
  version: 1.0.0
  title: Spendy - Expense Tracker App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: API documentation of Spendy Expense Tracker App

tags:
  - name: Users
    description: Operations about users.
  - name: Auth
    description: Auth operations.
  - name: Transactions
    description: Operations related to user transactions.

servers:
  - url: http://localhost:3000
  - url: https://example.com/api/v1

paths:
  /categories:
    get:
      $ref: ../swagger/paths/categories/get.yaml

  /rates:
    get:
      $ref: ../swagger/paths/currencies/get.yaml

  /statistics/summary:
    get:
      $ref: ../swagger/paths/statistics/summary.yaml

  /transactions:
    get:
      $ref: ../swagger/paths/transactions/get.yaml

  /transactions/{id}:
    delete:
      $ref: ../swagger/paths/transactions/{id}/delete.yaml
    put:
      $ref: ../swagger/paths/transactions/{id}/put.yaml

  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout/post.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
